#!/bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

# workspace names
bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9
bspc monitor DP1-3 -d 1 2 3 4 5 6 7 8 9
bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 9
#bspc monitor -d 1 2 3 4 5

# basic settings
bspc config window_gap		12
bspc config split_ratio		0.52
bspc config borderless_monocle	true
bspc config gapless_monocle	true
bspc config top_padding 	0
bspc config bottom_padding	27
bspc config border_width	0

# pointer and focus follow each other
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

# border colors
bspc config focused_border_color	\#517b58
bspc config normal_border_color		\#517b58

# mouse settings
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner

# startup
picom -b
feh --bg-fill $HOME/.config/wall.png
$HOME/.config/polybar/launch.sh
dunst &

# rules
bspc rule -a feh state=floating
bspc rule -a mpv state=pseudo_tiled
